name: 'template'
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  logging: ^1.2.0
  hooks_riverpod: ^2.4.0
  google_fonts: ^5.1.0
  go_router: ^10.1.2
  intl: ^0.18.1
  riverpod_annotation: ^2.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.1
  flutter_gen_runner: ^5.3.1
  custom_lint: ^0.5.3
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/